version: "3.7"

services:
  sonarqube:
    image: registry.libraries.homelab/sonarqube:latest
    container_name: sonarqube
    restart: always
    volumes:
      - ${ETC_LOCALTIME}:/etc/localtime:ro
      - ./init/sonar.properties:/opt/sonarqube/conf/sonar.properties
      - sonarqube-conf:/opt/sonarqube/conf
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
      - sonarqube-extensions:/opt/sonarqube/extensions
      #- ./backup:/app/backup
      #- ../certificados/:/certs/
    networks:
      net-proxy:
      net-ldap:
      net-database-sqlserver:
      net-sonarqube:
        aliases:
          - sonarqube.homelab
    environment:
      - TZ=America/Maceio
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=????
      - sonar.jdbc.url=jdbc:sqlserver://mssql:1433;databaseName=sonar
    labels:
      - traefik.enable=true
      - traefik.docker.network=net-proxy
      - traefik.frontend.rule=Host:sonarqube.homelab
      - traefik.frontend.passHostHeader=true
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.backend=sonarqube
      - traefik.port=9000
      
    # healthcheck:
    #   test: curl --fail -s http://localhost:9000/api/system/status || exit 1
    #                                              api/system/health
    #   start_period: 10s #default: 0s
    #   interval: 1m #default: 30s
    #   timeout: 5s #default: 30s
    #   retries: 5 #default: 3

volumes:
  sonarqube-conf:
    external: true
  sonarqube-data:
    external: true
  sonarqube-logs:
    external: true
  sonarqube-extensions:
    external: true

networks:
  net-proxy:
    external: true
  net-ldap:
    external: true
  net-database-sqlserver:
    external: true
  net-sonarqube:
    external: true
